version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: minecraft_bot_db
    restart: always
    environment:
      # Имя БД
      POSTGRES_DB: guide_db
      # Пользователь
      POSTGRES_USER: postgres
      # Пароль (лучше вынести в .env, но для старта ок)
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data # Сохраняем данные при перезапуске
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bot-network

  app:
    build: .
    container_name: minecraft_bot_app
    restart: on-failure
    depends_on:
      db:
        # БД запустится (будет в кондиции)
        condition: service_healthy
    environment:
      # Переопределяем настройки из application.yml
      # В Docker хост БД - это имя сервиса ("db"), а не localhost
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/guide_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      
      # Токены передаем здесь, чтобы не хранить их в коде
      # Эти переменные должны считываться в application.yml через ${VAR_NAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    networks:
      - bot-network

# Тома для хранения данных
volumes:
  pgdata:

# Сеть для общения контейнеров
networks:
  bot-network:
    driver: bridge
