server:
  port: 8080

telegram:
  bot:
    token: ${BOT_TOKEN}

spring:
  application:
    name: minecraft-helper-bot

  datasource:
    url: ${DB_URL}       # Например: jdbc:postgresql://db:5432/minecraft_bot
    username: ${DB_USER} # Например: postgres
    password: ${DB_PASS} # Например: superPassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Flyway создаст таблицы
    show-sql: false      # Включать только для отладки

  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always # Показывать подробности (место на диске, статус БД)
  metrics:
    tags:
      application: ${spring.application.name}